# MeDoc Configuration File

# Project paths
projectPath: "/Users/mekari/Documents/mobile-talenta"
outputPath: "./docs"

# Ollama AI Model Settings
modelName: "deepseek-coder"  # Use smaller model for large projects
temperature: 0.9
# contextLength: 4096
verbose: true

# Performance tuning
maxFilesPerBatch: 5        # Process 5 files at a time
delayBetweenBatches: 5000  # Wait 5 seconds between batches
maxFilesToProcess: 0       # Limit to first N files (0 for all files)
maxTags: 5                 # Limit to 5 most recent tags for changelog (0 for all tags)

# Generation options
overviewOnly: true         # Generate only project-level docs, not individual file docs

# Documentation settings
excludePaths:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "lib/generated/**"
  - "lib/gen/**"
  - "**/test/**"
  - "**/*.lock"

# Output format
format: "markdown"